# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Module-Rename
version:      0.03
version_from: lib/Module/Rename.pm
installdirs:  site
requires:
    Log::Log4perl:                 0.47
    Sysadm::Install:               0.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
